### PR TITLE
Gh982: Add full release date to ltnews

### PR DESCRIPTION
**Pull request by muzimuzhi**
**READ ME FIRST**: Please understand that in most cases we will not be able to merge a pull request because there are a lot of internal activities needed when updating the LaTeX2e sources. If you have a code suggestion please discuss it with the team first.

*Pull requests in this repository are intended for LaTeX Team members only.*

# Internal housekeeping

Since most of the releases happen on 1st of a month, `\publicationday{01}` is set in `ltnews.cls`. This also avoids modifying every existing `ltnews<n>.tex`.

```bash
grep -rhe '# [^ ]* Release' changes.txt | grep -ve '[/-]01 '
# 2021-11-15 Release
# 2020-02-02 Release
# 2017-04-15 Release
# 2011/06/27 Release
# 2009/09/24 Release
```

implements #982

**Previews**
image
image
image
image
image

**Discussion**
- Full release date is also added to the toc entry, is it acceptable?
- PDF bookmark titles are not modified.
   image

## Status of pull request

- [x] Feedback wanted 
- Under development
- [x] Ready to merge

## Checklist of required changes before merge will be approved
- [ ] Test file(s) added
- [ ] Version and date string updated in changed source files
- [ ] Relevant `\changes` entries in source included
- [x] Relevant `changes.txt` updated
- [ ] `ltnewsX.tex` (and/or `latexchanges.tex`) updated

### CODE REVIEW

**Review by FrankMittelbach — APPROVED** [review]
Looks good to me

**Review by FrankMittelbach — COMMENTED** [review]
However, perhaps we also want to add a short note to ltnews37 explaining the significance of that (...) and why it is helpful when using \NeedsTeXFormat or \IfFormatAtLeast...

**Comment by josephwright** [comment]
@FrankMittelbach  Agreed but can we merge here then deal with it directly on `develop`?

**Comment by FrankMittelbach** [comment]
> @FrankMittelbach Agreed but can we merge here then deal with it directly on `develop`?

sure as long as we don't forget :-)

**Pull request merged**
