### PR TITLE
ext@table for issue #561

### PR DESCRIPTION
**Pull request by davidcarlisle**
**READ ME FIRST**: Please understand that in most cases we will not be able to merge a pull request because there are a lot of internal activities needed when updating the LaTeX2e sources. If you have a code suggestion please discuss it with the team first.

*Pull requests in this repository are intended for LaTeX Team members only.*

# Internal housekeeping

## Status of pull request

- Feedback wanted 
- Under development
- Ready to merge

## Checklist of required changes before merge will be approved
- [X] Test file(s) added
- [X] Version and date string updated in changed source files
- [X] Relevant `\changes` entries in source included
- [X] Relevant `changes.txt` updated
- [X] `ltnewsX.tex` updated

### CODE REVIEW

**Review by FrankMittelbach — COMMENTED** [review]
not sure what to make of this ... this is only the tests but not the change is it?
but the pull claims it contains ltnews and changes and ... :-) am I missing something?

**Comment by davidcarlisle** [comment]
@FrankMittelbach You'd think I'd never used git before... sorry.

**Review by FrankMittelbach — APPROVED** [review]
that looks better :-)

**Comment by car222222** [comment]
Also a missing 's' here:

* longtable.dtx: write lits

**Comment by davidcarlisle** [comment]
@car222222  thanks:  s added

**Pull request merged**
