### PR TITLE
pdfspace metric change (reflected in test files)

### PR DESCRIPTION
**Pull request by FrankMittelbach**
# Internal housekeeping

## Status of pull request

- Ready to merge

@josephwright: I made this one against dev, but I just realized that they also need updating in main since it is an engine change that we reflect. Best course of action?

### CODE REVIEW

**Comment by josephwright** [comment]
Easiest is if I simply merge locally to both main and dev - looks OK to me.

**Review by u-fischer — APPROVED** [review]
Looks fine (assuming that you didn't miss one and the test passes now).

**Comment by FrankMittelbach** [comment]
> Looks fine (assuming that you didn't miss one and the test passes now).

that's what the pr claims :-)

**Comment by muzimuzhi** [comment]
Somehow the (HEAD of) `develop` branch after this PR was merged didn't pass the CI in my fork. See https://github.com/muzimuzhi/latex2e/actions/runs/9647632683/job/26609260678.

**Comment by u-fischer** [comment]
@muzimuzhi looks as if your ctan mirrors hasn't yet the updated tfm. It will probably run tomorrow.

**Comment by muzimuzhi** [comment]
@u-fischer Thanks. You're right.

Running `tlmgr update --list` then I noticed the corresponding change of `pdftexspace.tfm`, in TeX Live [r71605](https://tug.org/svn/texlive?view=revision&revision=71605). After `tlmgr` updating, my local `l3build check -q --show-log-on-error -c config-float` (executed in `./required/latex-lab`) passes.

**Pull request merged**
