### PR TITLE
Gh1359 b

### PR DESCRIPTION
**Pull request by FrankMittelbach**
Internal housekeeping

## Status of pull request

- Ready to merge (for this or the next release)

## Checklist of required changes before merge will be approved
- [x] Test file(s) added
- [x] Version and date string updated in changed source files
- [x] Relevant `\changes` entries in source included
- [x] Relevant `changes.txt` updated
- [n/a] Rollback provided (if necessary)?
- [n/a] `ltnewsX.tex` (and/or `latexchanges.tex`) updated

### CODE REVIEW

**Review by josephwright — APPROVED** [review]
Looks good. Will need to go into develop and main: I will do that if necessary.

**Review by davidcarlisle — APPROVED** [review]
looks good to me too modulo ongoing discussion of whether to remove the ids. In most cases it should be enough to simply expand the mark so let the ids go, so I think this is OK.

**Comment by FrankMittelbach** [comment]
> looks good to me too modulo ongoing discussion of whether to remove the ids. In most cases it should be enough to simply expand the mark so let the ids go, so I think this is OK.

but this *is* removing the marks, eg if you do `\FirstMark...` what is returned is the original  data without the mark now. one could use the data without that removal but this way it is simpler for use cases like the one Pieter outlined.

**Comment by davidcarlisle** [comment]
> > looks good to me too modulo ongoing discussion of whether to remove the ids. In most cases it should be enough to simply expand the mark so let the ids go, so I think this is OK.
> 
> but this _is_ removing the marks, eg if you do `\FirstMark...` what is returned is the original data without the mark now. one could use the data without that removal but this way it is simpler for use cases like the one Pieter outlined.

sorry use:v  yes all good then,

**Pull request merged**
