### PR TITLE
Define Unicode input for U+3008/U+3009

### PR DESCRIPTION
**Pull request by zauguin**
As mentioned in #714 we currently allow `U+2329` and `U+232A` to input `\textlangle` and `\textrangle`.
In order not to break documents when they are normalized we should therefore also allow their canonical equivalents `U+3008/U+3009`.

# Internal housekeeping

## Status of pull request

- Ready to merge

## Checklist of required changes before merge will be approved
- [ ] Test file(s) added
- [x] Version and date string updated in changed source files
- [x] Relevant `\changes` entries in source included
- [x] Relevant `changes.txt` updated
- [x] `ltnewsX.tex` (and/or `latexchanges.tex`) updated

### CODE REVIEW

**Comment by davidcarlisle** [comment]
I'm not sure that this is the right thing to do. U+3008/U+3009 are the CJK punctuation characters and if you map them to math angle brackets that breaks that use. The normalisation is from 2329 to 3008 which would mean that 2329 shouldn't be a math character rather than making 3008 a math character.  The whole thing is a mess which is why 2329 is essentially deprecated and 27E8 introduced which was seen as prefereable to breaking the stability rules and removing the normalisaion.

That said, the definitions can be over-written so if a CJK package redefined  U+3008 to be a suitable angle bracket having it default to a math angle bracket in the absense of such a package wouldn't be the end of the world.

A purer but perhaps less kind alternative would be to undeclare 2329 to match the undeclared 3008 so neither are usable by default.

**Comment by zauguin** [comment]
> A purer but perhaps less kind alternative would be to undeclare 2329 to match the undeclared 3008 so neither are usable by default.

I do agree that that would be a nicer alternative *if* we are willing to break documents using U+2329/U+232A.

> U+3008/U+3009 are the CJK punctuation characters and if you map them to math angle brackets that breaks that use.

The question is IMO what the alternative looks like. Of course it's best to use actual CJK punctuation for these, but if there are alternative meanings for U+3008/U+3009 defined they should overwrite these anyway. If there are no alternatives defined, I would assume that using characters which are designed for mathematical use is still better than missing characters for CJK use. (Especially for CJK documents using non Unicode engines)
That leaves code which hooks into the undefined character handling, but even such code should be rather easy to adapt to add explicit cases for these.

> The normalisation is from 2329 to 3008 which would mean that 2329 shouldn't be a math character rather than making 3008 a math character.

But are we doing that? The suggestion is to map these to `\textlangle` and `\textrangle` which I would assume on a LICR to refer to a non-math angle bracket. For many font encodings these might actually be implemented as math characters since no non-math brackets are available, but I would see that more as a best effort fallback than as a classification of `\text[lr]angle` as a fundamentally mathematical character.

**Comment by zauguin** [comment]
Generally I see four options here:

  1. Map U+3008/U+3009 to `\textlangle`/`\textrangle`.
  2. Unmap U+2329/U+232A.
  3. Map all four codepoint to something else™
  4. Keep the inconsistent handling of U+2329/U+232A and U+3008/U+3009.

Personally I think that we really should avoid option 4 since it leads to documents which break under mysterious circumstances and more generally is rather impractical in a modern Unicode workflow. I have no good suggestion what the "something else" in 3 would look like, so this leaves 1 or 2.

I would go for 1 since `\textlangle/\textrangle` already seems to express a fundamentally non mathematical nature (even though it might end up being implemented with mathematical characters) and to ensure as much compatibility as possible, but I wouldn't object to option 2 either. After all U+2329 and U+232A have been deprecated for more than a decade.

**Comment by davidcarlisle** [comment]
ah I was thinking that we map U+2329 to \langle (math) I agree with
\textlangle it's a more or less plausible fallback for U+3008 as well so OK
let's do that.

**Pull request merged**
