### PR TITLE
fix small typos in latex-lab

### PR DESCRIPTION
**Pull request by mbertucci47**
Fixes a few small typos in the latex-lab bundle.

# Internal housekeeping

## Status of pull request

- Ready to merge

## Checklist of required changes before merge will be approved
- [ ] Test file(s) added
- [x] Version and date string updated in changed source files
- [ ] Relevant `\changes` entries in source included
- [ ] Relevant `changes.txt` updated
- [ ] Rollback provided (if necessary)?
- [ ] `ltnewsX.tex` (and/or `latexchanges.tex`) updated

### CODE REVIEW

**Comment by FrankMittelbach** [comment]
Given that your corrections also involve debugging data the tests for tables all fail and would need regeneration. Probably running `sh update-table.sh` will fix that (unless it is incomplete, which happens).

**Comment by mbertucci47** [comment]
Sorry about that. I ran `sh update-table.sh` but it didn't end up changing any files

**Comment by muzimuzhi** [comment]
@mbertucci47 After adding `table-016-math` to the list of test names updated by `l3build save -cconfig-table-pdftex <name>...` in `./required/latex-lab/update-table.sh`, running `sh update-table.sh` in subdirectory `./required/latex-lab` works for me.
```diff
diff --git a/required/latex-lab/update-table.sh b/required/latex-lab/update-table.sh
index a96ca314..68c0f582 100644
--- a/required/latex-lab/update-table.sh
+++ b/required/latex-lab/update-table.sh
@@ -20,6 +20,7 @@ l3build save -cconfig-table-pdftex \
        table-014-pbox-longtable \
        table-015 \
        table-016 \
+       table-016-math \
        table-017 \
        table-018 \
        table-019 \
```

**Comment by mbertucci47** [comment]
@muzimuzhi Thanks for investigating. After changing the .sh file, I still can't get the files to change. After running `sh update-table.sh` the terminal shows
```
update-table.sh: line 31: table-000: command not found
update-table.sh: line 32: table-001: command not found
update-table.sh: line 33: table-001-pdf: command not found
```
and so on. This could be because I'm on windows so running bash through wsl and my texlive there is the not-up-to-date apt version. Or a different issue with running it through wsl

**Comment by muzimuzhi** [comment]
@mbertucci47 Another option is to first run `l3build check` with `--show-saves/-S` option (and possibly restricted configs), which then will auto-generate `l3build save -c<config> <name>...` command needed to regenerate failed tests.

For example running (in subdirectory `./required/latex-lab`)
```
l3build check -c onfig-table-pdftex,config-table-luatex --show-saves -q
```
would end with stdout
```
Failed tests for configuration "config-table-pdftex":

  ...

Failed tests for configuration "config-table-luatex":

  ...

To regenerate the test files, run

  l3build save -c config-table-pdftex table-021-longtable table-020 table-009 table-012-caption table-017 table-004-tabularx table-002 table-005 table-003 table-007-longtable table-006-longtable table-001 table-019 table-016-math table-015 table-008-multi
  l3build save -c config-table-luatex table-003 table-005 table-002 table-008-multi table-004-tabularx table-001 table-021-longtable table-009 table-007-longtable table-006-longtable

To detect engine-specific differences, run after that

  l3build check --show-saves -c config-table-pdftex ...
  l3build check --show-saves -c config-table-luatex ...
```

**Comment by mbertucci47** [comment]
Test files should now be updated, and `table-016-math \` was added to `update-table.sh`

**Comment by FrankMittelbach** [comment]
> Test files should now be updated, and `table-016-math \` was added to `update-table.sh`

looks good, thanks

**Pull request merged**
