### PR TITLE
Remove unused local variable `tex_setattribute` in `ltluatex.lua`

### PR DESCRIPTION
**Pull request by Josef-Friedrich**

### CODE REVIEW

**Comment by josephwright** [comment]
Change is logical, but we need the various bits of admin doing:

- Change the file date and version for the `.dtx`
- Add a `\changes` line
- Include in `changes.txt`

**Comment by Josef-Friedrich** [comment]
Thank you very much for your review. Hopefully I have documented the change correctly.

**Comment by josephwright** [comment]
Close enough ;) I'll fix the order issue in `changes` myself.

**Comment by josephwright** [comment]
Based on the test failure, are you _sure_ this is unused (@zauguin - thoughts)

**Comment by Josef-Friedrich** [comment]
When I opened the file ltluatex.lua in the vscode, it gave me an warning about an unused local variable:

Screenshot from 2023-01-20 16-59-42

When I search for the `tex_setattribute` in the file https://github.com/latex3/latex2e/blob/develop/base/ltluatex.dtx it finds only one occurrence: the definition of the local variable itself.

**Review by zauguin — APPROVED** [review]

**Review by davidcarlisle — APPROVED** [review]
2 tests fail due to a change in the line numbers in the log.
I'll approve/merge then adjust here.

**Pull request merged**
