### PR TITLE
Update ltnews33.tex

### PR DESCRIPTION
**Pull request by sieversMartin**
Fix typo

**READ ME FIRST**: Please understand that in most cases we will not be able to merge a pull request because there are a lot of internal activities needed when updating the LaTeX2e sources. If you have a code suggestion please discuss it with the team first.

*Pull requests in this repository are intended for LaTeX Team members only.*

# Internal housekeeping

## Status of pull request

- Feedback wanted 
- Under development
- Ready to merge

## Checklist of required changes before merge will be approved
- [ ] Test file(s) added
- [ ] Version and date string updated in changed source files
- [ ] Relevant `\changes` entries in source included
- [ ] Relevant `changes.txt` updated
- [ ] `ltnewsX.tex` updated

### CODE REVIEW

**Comment by car222222** [comment]
Thanks for spotting this, Martin.

We shall not use this PR to make the change since we are revising the whole document.

**Comment by sieversMartin** [comment]
Is this still the best way to report typos?

**Comment by FrankMittelbach** [comment]
@sieversMartin well yes and no. For a single typo it is clearly an overkill :-) on the other hand it means it is recorded. But with something like ltnews during development that gets changed so much around that pulling things in, usually just doesn't work. With documentation typos against code files (on development) those are more likely to just being mergeable.

Anyway I fixed it in the branch where we currently descting ltnews33.

**Comment by blefloch** [comment]
Some other people have provided similar fixes as comments on the commit on github.  Here, that would mean
1. Navigate from https://github.com/latex3/latex2e/ to the specific file in the develop branch, namely https://github.com/latex3/latex2e/blob/develop/base/doc/ltnews33.tex
2. Select the line, click on the menu (three dots) and select "git blame" to find out what commit touched that line last, namely https://github.com/latex3/latex2e/commit/a7519f2f48242c2336fdc6f9f78216a1eebfcef7
3. There, leave your comment by clicking on the line (on the blue plus that shows up when hovering).

In practice, you often have the commit right away since comments often arise when reading through diffs, so you can leave a comment directly.

**Pull request closed without merging**
