### PR TITLE
updated and integrated ltpara

### PR DESCRIPTION
**Pull request by FrankMittelbach**
# Internal housekeeping

## Status of pull request

- Ready to merge

hopefully complete

## Checklist of required changes before merge will be approved
- [x] Test file(s) added
- [x] Version and date string updated in changed source files
- [x] Relevant `\changes` entries in source included
- [x] Relevant `changes.txt` updated
- [x] `ltnewsX.tex` updated

### CODE REVIEW

**Comment by u-fischer** [comment]
Is the sentence in the documentation for \Omitindent  that the box remains available for use still correct? It seems to contradict a bit the description in  the hooks (but perhaps I misunderstand the "for use" meaning).

**Comment by car222222** [comment]
The code is thus:

%     The declaration \cs{para_omit_indent:} (or
%    \cs{OmitIndent}) changes that to do nothing.
%    \begin{macrocode}
\cs_new:Npn \para_omit_indent: {
  \box_gclear:N \g_para_indent_box
}

So I think that the sentence should be removed.  (I am not too sure what it meant even with the previous behaviour.)

The above phrase "changes that to do nothing" is also not very helpful.  Partly because the way the code works is rather more complex.  

I can deal with both of these when I go over all the documentation (when I get a 'round too-wit':-).

**Comment by FrankMittelbach** [comment]
> So I think that the sentence should be removed. (I am not too sure what it meant even with the previous behaviour.)
> 
> The above phrase "changes that to do nothing" is also not very helpful. Partly because the way the code works is rather more complex.
> 
> I can deal with both of these when I go over all the documentation (when I get a 'round too-wit':-).

that loooks like leftover documentation where the code got updated but the documentation is still from the earlier implementation, sorry for that. So yes, that needs updating.

**Comment by car222222** [comment]
Really just a note to myself!

This last sentence here also got left over:

% \begin{variable}{\IndentBox,\g_para_indent_box}
%    The box register holding the indentation box for the paragraph is
%    available for inspection (or changes) inside hooks. It remains
%    available even if the \cs{OmitIndent} command was
%    used; in that case it  will just not be automatically placed.

**Pull request merged**
