### PR TITLE
Robust crs

### PR DESCRIPTION
**Pull request by FrankMittelbach**
# Internal housekeeping

## Status of pull request

- Ready to merge

longtable change in separate pr

## Checklist of required changes before merge will be approved
- [x] Test file(s) added
- [x] Version and date string updated in changed source files
- [x] Relevant `\changes` entries in source included
- [x] Relevant `changes.txt` updated
- [ ] `ltnewsX.tex` updated (only placeholder yet)

### CODE REVIEW

**Review by car222222 — APPROVED** [review]
There is, I think, another sneaky one in ltmath:

Inside the definition of eqnarray* \@eqncr gets redefined and so needs to be \protected here:

\let\@seqncr=\@eqncr

\@namedef{eqnarray*}{\def\@eqncr{\nonumber\@seqncr}\eqnarray}



\@stackcr

**Comment by car222222** [comment]
That @stackcr should have been deleted.

I believe that all the \\ in the kernel plus amsmath and array are fixed now.

**Comment by FrankMittelbach** [comment]
> That @stackcr should have been deleted.

sorry, means what?

**Comment by FrankMittelbach** [comment]
> Inside the definition of eqnarray* @eqncr gets redefined and so needs to be \protected here:
> 
> \let@seqncr=@eqncr
> 
> @namedef{eqnarray*}{\def@eqncr{\nonumber@seqncr}\eqnarray}

has happened by now

**Comment by car222222** [comment]
Deleted from the end of my previous comment.

All OK now.

**Pull request merged**
