### PR TITLE
Correct remove from \@unusedoptionlist

### PR DESCRIPTION
**Pull request by josephwright**
**READ ME FIRST**: Please understand that in most cases we will not be able to merge a pull request because there are a lot of internal activities needed when updating the LaTeX2e sources. If you have a code suggestion please discuss it with the team first.

*Pull requests in this repository are intended for LaTeX Team members only.*

# Internal housekeeping

## Status of pull request

- Feedback wanted 
- Under development
- [X] Ready to merge

## Checklist of required changes before merge will be approved
- [X] Test file(s) added
- [X] Version and date string updated in changed source files
- [X] Relevant `\changes` entries in source included
- [X] Relevant `changes.txt` updated
- [ ] `ltnewsX.tex` (and/or `latexchanges.tex`) updated

### CODE REVIEW

**Review by davidcarlisle — APPROVED** [review]
looks better this time thanks, still PL1 but perhaps you fix that up when tagging a PL release?

**Comment by josephwright** [comment]
> looks better this time thanks, still PL1 but perhaps you fix that up when tagging a PL release?

You mean `changes.txt`? I'll do that after merging

**Review by FrankMittelbach — COMMENTED** [review]
is there a test file the records the correct behavior?

**Comment by josephwright** [comment]
@FrankMittelbach  Not yet, but I can create one I'm sure :)

**Comment by josephwright** [comment]
BTW, I've locally renamed the branch as `hotfix/gh864`, so if/when we are happy, I'll do the merge outside of GitHub so that shows properly.

**Comment by davidcarlisle** [comment]
no I meant ltvers.dtx, but after merge is probably the right thing anyway as l3build tagging will catch that later

**Comment by josephwright** [comment]
@davidcarlisle  Ah: that gets done only when I do the release cycle

**Pull request merged**
