### PR TITLE
Move lualatex math

### PR DESCRIPTION
**Pull request by u-fischer**
**READ ME FIRST**: Please understand that in most cases we will not be able to merge a pull request because there are a lot of internal activities needed when updating the LaTeX2e sources. If you have a code suggestion please discuss it with the team first.

*Pull requests in this repository are intended for LaTeX Team members only.*

# Internal housekeeping

## Status of pull request

- Ready to merge, nearly there seem to be a conflict in ltnews32.tex but I don't quite see why so leave it better open.

## Checklist of required changes before merge will be approved
- [x] Test file(s) added
- [x] Version and date string updated in changed source files
- [x] Relevant `\changes` entries in source included
- [x] Relevant `changes.txt` updated
- [x] `ltnewsX.tex` updated

### CODE REVIEW

**Review by davidcarlisle — APPROVED** [review]

**Review by FrankMittelbach — APPROVED** [review]

**Comment by davidcarlisle** [comment]
@u-fischer  @FrankMittelbach  who's doing the merge (and fixing ltnews conflict) ? I could if you are not...:-)

**Comment by FrankMittelbach** [comment]
Am 27.09.20 um 13:04 schrieb David Carlisle:
> @u-fischer <https://github.com/u-fischer> @FrankMittelbach 
> <https://github.com/FrankMittelbach> who's doing the merge (and fixing 
> ltnews conflict) ? I could if you are not...:-)

I have a board meeting this afternoon, so only time this evening but I 
do it then if not done

would be good if the ltnews32 update is minimal invasive as it is 
already copy-edited and adjusted for TUB printing

**Comment by davidcarlisle** [comment]
@FrankMittelbach  the ltnews32 conflict is one space character at end of one line, I don't think it'll need a lot of proof reading:-)

**Comment by u-fischer** [comment]
@davidcarlisle  well I did add a paragraph (but pulled first the version from develop).  So it has changed more than a space.

But when I compile locally the outcome looks quite okay:

image

**Comment by davidcarlisle** [comment]
@u-fischer  yes there is an additional paragraph but that didn't cause a conflict, the conflict was just the previous paragraph with different source white space.

**Comment by FrankMittelbach** [comment]
> but that didn't cause a conflict

but it may need copy-editing (my additions usually do :-) )

**Comment by car222222** [comment]
@FrankMittelbach "but it may need copy-editing (my additions usually do :-) )"

Such as 'For quite some years . . . '?  :-)

**Comment by FrankMittelbach** [comment]
> Such as 'For quite some years . . . '? :-)

yep, but innocent your Honor (this time)

**Pull request merged**
