### PR TITLE
Set \oe/\OE equal during case changing

### PR DESCRIPTION
**Pull request by josephwright**
# Internal housekeeping

## Status of pull request

- Feedback wanted 
- Under development
[X] Ready to merge

## Checklist of required changes before merge will be approved
- [ ] Test file(s) added
- [X] Version and date string updated in changed source files
- [X] Relevant `\changes` entries in source included
- [X] Relevant `changes.txt` updated
- [ ] `ltnewsX.tex` (and/or `latexchanges.tex`) updated

### CODE REVIEW

**Review by davidcarlisle — COMMENTED** [review]
This looks fine as far as it goes but can you say a bit why just oe needs this and not other entries of the old list, which are presumably handled OK by the underlying L3 code?

```
\def\@uclclist{\oe\OE\o\O\ae\AE
      \dh\DH\dj\DJ\l\L\ng\NG\ss\SS\ij\IJ\th\TH}
```

**Comment by josephwright** [comment]
@davidcarlisle  It's because `\oe`/`\OE` are used as a marker by `babel`:
```
> \bbl@cased=macro:
->\ifx \oe \OE \expandafter \in@ \expandafter {\expandafter \OE \expandafter }\
expandafter {\oe }\ifin@ \bbl@afterelse \expandafter \MakeUppercase \else \bbl@
afterfi \expandafter \MakeLowercase \fi \else \expandafter \@firstofone \fi 
```

**Comment by davidcarlisle** [comment]
>  It's because \oe/\OE are used as a marker by babel:

blrg OK  PR approved, but we should add this as a comment to the code

**Review by FrankMittelbach — COMMENTED** [review]
given that this is (if you will) a temporary fix because of that somewhat strange method in babel right now, I think it would have been better placed into firstaid, as I think it is something that shold go out eventually again.

on the other hand we can certainly take it out of ltfinal, so given that it is already there ...

why is the test file getting an additional space? is that correct?

**Comment by josephwright** [comment]
I'm happy adding to `firstaid` if that feels cleaner.

**Comment by FrankMittelbach** [comment]
> I'm happy adding to `firstaid` if that feels cleaner.

well, firstaid differs in main and dev so it is probably not wirth the bother now that it is already in.

**Comment by josephwright** [comment]
@FrankMittelbach  Space looks like an issue with having `\label` at the end of a text-cased string followed by a space vs not followed by a space: that's something I'll need to look at in the `expl3` code.

**Comment by josephwright** [comment]
@FrankMittelbach  Thinking a bit more: it's because without the extra tokens, case changing gives ` \label{A} `, so the two spaces are combined, but now we get ` \label{A}<stuff> `, so they don't. To-be expected.

**Comment by FrankMittelbach** [comment]
wait a second and let me understand that. why is a change in the outcome "to be expected"? All we did was changing the \MakeUppercase internal code so  documents should not change (unless they uppercased incorrectly in the past. (I must confess that I haven't looked what the test does ...)

**Comment by josephwright** [comment]
> wait a second and let me understand that. why is a change in the outcome "to be expected"? All we did was changing the \MakeUppercase internal code so documents should not change (unless they uppercased incorrectly in the past. (I must confess that I haven't looked what the test does ...)

The test has `\MakeUppercase{a \label{b}} c`. If you set up case changing to be pure `f`-type expansion, this becomes, `A \label{b} c`, and then `\label` does it's thing and we see `a c`. However, if there are any tokens at the end of `\MakeUppercase` after the pure-expansion step, they mean we get `A \label{b}<tokens> c`, the two spaces are not compressed and we see them both in the output.

**Comment by FrankMittelbach** [comment]
But that would be a clear change of functionality, wouldn't it?  and not unlikely to affect documents

**Comment by davidcarlisle** [comment]
Until this year makeuppercase used a `{}` group so  a `\ignorespaces` in label would have no effect so it is reverting to that, but if we are thinking this is just temporary it might be good to avoid churn here at least in the kernel version. Perhaps we should leave this for babel to patch if needed?

**Comment by u-fischer** [comment]
can't babel detect the context in a more natural way now or use \CaseSwitch?

**Comment by josephwright** [comment]
@u-fischer  That will only work if it's reached by expansion of the input, not the way `babel` uses `\bbl@cased` (hidden inside protected macros).

**Comment by FrankMittelbach** [comment]
> Until this year makeuppercase used a `{}` group so a `\ignorespaces` in label would have no effect so it is reverting to that, but if we are thinking this is just temporary it might be good to avoid churn here at least in the kernel version. Perhaps we should leave this for babel to patch if needed?

ah, so we overlooked that change back then and are now reverting to it. If that was always the case then I'm fine with it even if it was different in the last months. Otherwise it should have been documented (at least).

**Review by FrankMittelbach — APPROVED** [review]

**Comment by jbezos** [comment]
My OK is late, but it's an OK.

**Pull request merged**
