### PR TITLE
Add support for "\={i}" to OT1 and T1

### PR DESCRIPTION
**Pull request by josephwright**
# Internal housekeeping

## Status of pull request

- Feedback wanted 
- Under development
- [x] Ready to merge

## Checklist of required changes before merge will be approved
- [ ] Test file(s) added
- [x] Version and date string updated in changed source files
- [x] Relevant `\changes` entries in source included
- [x] Relevant `changes.txt` updated
- [ ] Rollback provided (if necessary)?
- [ ] `ltnewsX.tex` (and/or `latexchanges.tex`) updated

I'm not seeing a need for rollback here or a news entry as this is an edge case - but if I'm wrong, do say!

### CODE REVIEW

**Review by FrankMittelbach — APPROVED** [review]
approved, but something fails in the source2e documentation

**Comment by josephwright** [comment]
> approved, but something fails in the source2e documentation

I'll look - I guess `\changes`

**Comment by FrankMittelbach** [comment]
> Ah, it's the `=` - suggested alternative to
> 
> ```
> % \changes{v2.1b}{2024/11/04}{Support \cs{=}\cs{i} for OT1}
> ```
> 
> ?

what is breaking there?

**Comment by josephwright** [comment]
> what is breaking there?

From `source2e.gls`:
```latex
  \item 2024-11-04 ltoutenc.dtx v2.1b\efill 
 \subitem General:\ }\cs {i} for T1\pfill \hdpindex{}{490}
```

**Comment by davidcarlisle** [comment]
`gind,ist` akes `=` the actual-char.  `\changes... support i-macron accent in OT1` would avoid falling over =

**Comment by FrankMittelbach** [comment]
> `gind.ist` makes `=` the actual-char. `\changes... support i-macron accent in OT1` would avoid falling over =

ah, as simple as that. But I though macros are entred with quote chars in front of everything ...hmm, anyway, changing the text is certainly easy enough for now.

**Comment by josephwright** [comment]
OK now?

**Pull request merged**
