### PR TITLE
Verb adjustments

### PR DESCRIPTION
**Pull request by josephwright**
*Pull requests in this repository are intended for LaTeX Team members only.*

# Internal housekeeping

## Status of pull request

- Feedback wanted 
- Under development
- [x] Ready to merge

## Checklist of required changes before merge will be approved
- [x] Test file(s) added
- [x] Version and date string updated in changed source files
- [x] Relevant `\changes` entries in source included
- [x] Relevant `changes.txt` updated
- [x] `ltnewsX.tex` (and/or `latexchanges.tex`) updated

### CODE REVIEW

**Comment by josephwright** [comment]
This is spun out from https://github.com/latex3/latex2e/pull/1087: these parts are all agreed so I will merge straight away.

**Comment by muzimuzhi** [comment]
`verbatim` and especially `verbatim*` environments are affected too, but not mentioned in ltnews entry and not tested in `github-1085.lvt`. `changes.txt` entry uses general phrase "verbatim material", thus one can deduce env-forms are already covered there.

**Comment by josephwright** [comment]
@muzimuzhi 1d781b2827141b478ad6bf0ca847f5d5fc2c7770 and 39a45d8f1e36b71fea9a2e8c9308d6718b0fd925 hopefully cover it.

**Comment by muzimuzhi** [comment]
Yes they do. Thanks.

**Comment by car222222** [comment]
Does this require any further review?  
In particular, of the documentation.

**Comment by josephwright** [comment]
@car222222  I extracted the commits from the other PR that were about `\verb*`, etc., including the doc updates I'd written there. So what's merged here is what had been agreed. That doesn't preclude taking another look at the docs, if you want, though I'm not sure where this would go (`\verb`, etc., are after all documented in Lamport's book).

**Comment by car222222** [comment]
OK.  I shall look at anything that has changed recently.

I rather doubt that Leslie wrote anything  treatment of tabs?

**Comment by car222222** [comment]
The only typo I spotted (so far:-) is a "mon-spaced".

**Comment by josephwright** [comment]
> I rather doubt that Leslie wrote anything about the treatment of tabs?

Definitely not - I meant that I'm not sure where one would adjust docs as the only official place I'm aware of is something we can't change.

**Comment by car222222** [comment]
That is probably a problem with other details in The Manual that are no longer exactly correct.

We could think about producing some kind of supplementary document covering all such items.

**Comment by car222222** [comment]
That is probably a problem with other details in The Manual that are no longer exactly correct.

We could think about producing some kind of supplementary document covering all such items.

**Comment by car222222** [comment]
That is probably a problem with other details in The Manual that are no longer exactly correct.

We could think about producing some kind of supplementary document covering all such items.

**Comment by car222222** [comment]
There is of course Karl's "unofficial manual":

https://texdoc.org/serve/latex2e.pdf/0

I think that he likes to keep this up-to-date with the latest tweaks.

**Comment by car222222** [comment]
Why have some comments been deleted here?

**Comment by josephwright** [comment]
@car222222  That was one that got posted three times saying the same thing - was just cleaning up what I assume was a GitHub issue

**Comment by car222222** [comment]
OK, fine? Thanks.

**Pull request merged**
