### PR TITLE
add \@currentcounter to \refstepcounter, gh300

### PR DESCRIPTION
**Pull request by u-fischer**
# Internal housekeeping

## Status of pull request

- Ready to merge (I hope ...)

## Checklist of required changes before merge will be approved
- [x] Test file(s) added
- [x] Version and date string updated in changed source files
- [x] Relevant `\changes` entries in source included
- [x] Relevant `changes.txt` updated
- [x] `ltnewsX.tex` updated

### CODE REVIEW

**Comment by FrankMittelbach** [comment]
why is this listing millions of files as changed? have you branched off from master instead of develop?

**Comment by u-fischer** [comment]
@FrankMittelbach  no I branched from develop, but first made the pull request against master and just corrected this.  For me the commit looks ok now.

**Comment by u-fischer** [comment]
@FrankMittelbach  but I don't quite understand what happened to the changes.txt, but will repair it.

**Comment by FrankMittelbach** [comment]
> @FrankMittelbach but I don't quite understand what happened to the changes.txt, but will repair it.

you also need to fix the test suite (the two files containing "-often" in their name. Whenever you add new guards they change because the test rollback and display the result.

**Pull request merged**
