### PR TITLE
cosmetics: show invalid bytes in hex, not decimal

### PR DESCRIPTION
**Pull request by mirabilos**
This was originally part of https://github.com/latex3/latex2e/pull/62 which was rejected (for now, and with reason), but independent of the rejected part, and so still should be merged.

### CODE REVIEW

**Comment by mirabilos** [comment]
Travis fails unrelatedly: https://github.com/latex3/latex2e/compare/bcccc7c42356...b2b32f2af1d7 introduced a change without adapting the testsuite, causing https://travis-ci.org/latex3/latex2e/builds/437124178 to fail.

**Comment by mirabilos** [comment]
The Travis failure is unrelated, as far as I can tell, and caused by a pre-existing bug.

**Comment by josephwright** [comment]
@mirabilos The Travis-CI failure relates to changes in LuaTeX/`luaotfload`: the team (@davidcarlisle and I) are aware of it!

**Comment by davidcarlisle** [comment]
Not really a bug just luatex changes again, I need to see if I can wrap the test suite to get the old log files back or whether we need to add (a lot of) new luatex-specific tlg files to match the new luatex log output, I'm hoping to avoid doing the latter....

**Comment by davidcarlisle** [comment]
I don't think there is need to add another decimal-to-hex macro, we could simply use

`Invalid UTF-8 byte "\UTFviii@hexnumber{`#1}`

as the only difference is the test for numbers less than 16 which doesn't apply here (as they are not invalid UTF-8)

**Comment by davidcarlisle** [comment]
Thanks slightly modified change adopted as noted above.

**Pull request closed without merging**
