### PR TITLE
remove spurious spaces (xcolor issue 10)

### PR DESCRIPTION
**Pull request by u-fischer**
**READ ME FIRST**: Please understand that in most cases we will not be able to merge a pull request because there are a lot of internal activities needed when updating the LaTeX2e sources. If you have a code suggestion please discuss it with the team first.

*Pull requests in this repository are intended for LaTeX Team members only.*

# Internal housekeeping

## Status of pull request

- Feedback wanted 
- Under development
- Ready to merge

## Checklist of required changes before merge will be approved
- [ ] Test file(s) added
- [x ] Version and date string updated in changed source files
- [x ] Relevant `\changes` entries in source included
- [x] Relevant `changes.txt` updated
- [ ] `ltnewsX.tex` (and/or `latexchanges.tex`) updated

### CODE REVIEW

**Comment by josephwright** [comment]
Needs to be in `changes.txt`

**Comment by yihui** [comment]
I wonder if this PR could be merged asap. We have been waiting for this bug fix for a week. It has affected about 70 R packages on CRAN. Thank you very much!

**Review by davidcarlisle — APPROVED** [review]

**Comment by FrankMittelbach** [comment]
it still needs a change log entry before it gets distributed

**Comment by davidcarlisle** [comment]
@yihui  we'll do what we can although I must say I'm surprised it has a big impact: as far as I can tell this should only be broken for documents that load both color and xcolor which is never needed, simply loading xcolor should be enough.

**Comment by yihui** [comment]
@davidcarlisle You were right---the broken R packages loaded both color and xcolor. The former was loaded through a template, and the latter was loaded by users. I haven't investigate why this happened yet, but I'll see if it's possible to replace `color` with `xcolor` in the template.

Thank you very much!

**Comment by davidcarlisle** [comment]
@yihui  I just pushed the change from develop to main branch and tests seem to pass so we should be able to push this out shortly anyway but I couldn't help asking:-)

**Comment by u-fischer** [comment]
> You were right---the broken R packages loaded both color and xcolor. 

Loading both is not really a problem, but loading color, defining a color and then loading xcolor will give you colors xcolor can not use and can lead to hard to spot problems. It is much safer if the template loads xcolor.

**Comment by yihui** [comment]
> It is much safer if the template loads xcolor.

That's what I hope to do. My only concern is about possible option clashes, i.e., I `\usepackage{xcolor}` in the template but users load it again with options later in the document. I need to check these R packages before I make this change.

**Comment by davidcarlisle** [comment]
@yihui  graphics bundle has been pushed to ctan, will take a couple of days to reach texlive normally

**Comment by yihui** [comment]
Perfect. Many thanks again!

**Comment by FrankMittelbach** [comment]
@yihui perhaps as a helpful hint for next time: errors happen even though we try to avoid them. But the upcoming release is always publicly available for about at least a month before it goes live and you can easily run your own test suite against it if you use pdflatex-dev or lualatex-dev on your system instead of the main pdflatex, lualate, xelatex. This way we can hopefully catch blunder like this one next time (if it is not caught by our own tests) before it is released as the main release. The more people do this the better the chances this works out perfectly.

**Comment by yihui** [comment]
@FrankMittelbach Great suggestion! I'll add a daily test in my package to discover possible problems early. Thanks!

**Comment by muzimuzhi** [comment]
Paying more attention to warnings may help as well, since

> loading color, defining a color and then loading xcolor

with older `color` package already gives warning

> Package xcolor Warning: Incompatible color definition on input line 6.

**Comment by FrankMittelbach** [comment]
> @FrankMittelbach Great suggestion! I'll add a daily test in my package to discover possible problems early. Thanks!

small caveat: directly after a new release (especially after a patch release) the -dev release may be initially a bit behind, for example right now  main is 2011-11-15 PL1 but dev is still 2022-06-01 (which is equiv to 2011-11 PL0) because we haven't yet put out a new, just because we are in the middle of preparing a real dev release, so that hotfix is not yet in. But close to the end of the release cycle dev will be exactly what will show up in the next release (except for final fixes due to testing by you, us and others). Hope that description makes sense but you find more on the LaTeX project website.

**Pull request merged**
