### PR TITLE
fix small typos in base dtx files

### PR DESCRIPTION
**Pull request by mbertucci47**
Fixes a few small typos in the base dtx files.

# Internal housekeeping

## Status of pull request

- Ready to merge

## Checklist of required changes before merge will be approved
- [ ] Test file(s) added
- [x] Version and date string updated in changed source files
- [ ] Relevant `\changes` entries in source included
- [ ] Relevant `changes.txt` updated
- [ ] Rollback provided (if necessary)?
- [ ] `ltnewsX.tex` (and/or `latexchanges.tex`) updated

### CODE REVIEW

**Comment by mbertucci47** [comment]
A test failed because I changed occured -> occurred in an error message in ltluatex.dtx. I can revert that change if it's a pain to fix the test files

**Comment by muzimuzhi** [comment]
@mbertucci47 Running `l3build save -eluatex tlb-callbacks-002` in `./base` directory should update `./base/testfiles/tlb-callbacks-002.luatex.tlg`, the only affected `.tlg` file.

**Comment by mbertucci47** [comment]
@muzimuzhi Thanks, done

**Review by muzimuzhi — APPROVED** [review]

**Review by FrankMittelbach — APPROVED** [review]
side remark: co-ordinate is the more common spelling in the UK as far as I know and both are "correct", but we might as well drop the hyphen since we lean towards US spelling (well some of us :-))

**Pull request merged**
