### PR TITLE
Correct handling of unknown option list (see #938)

### PR DESCRIPTION
**Pull request by josephwright**
**READ ME FIRST**: Please understand that in most cases we will not be able to merge a pull request because there are a lot of internal activities needed when updating the LaTeX2e sources. If you have a code suggestion please discuss it with the team first.

*Pull requests in this repository are intended for LaTeX Team members only.*

# Internal housekeeping

## Status of pull request

- Feedback wanted 
- Under development
- [X] Ready to merge

## Checklist of required changes before merge will be approved
- [ ] Test file(s) added
- [X] Version and date string updated in changed source files
- [X] Relevant `\changes` entries in source included
- [X] Relevant `changes.txt` updated
- [X] `ltnewsX.tex` (and/or `latexchanges.tex`) updated

### CODE REVIEW

**Review by davidcarlisle — CHANGES_REQUESTED** [review]
I think, in the end, this should work

```
\documentclass[foo,bar,baz=foo,ggg=\sqrt{4}]{myclass}
\usepackage{amsmath}
\begin{document}
\end{document}
```

It fails currently in file loading as I missed some `\protected@edef` in the PR for #933 
specifcally at least

```
diff --git a/base/ltclass.dtx b/base/ltclass.dtx
index 72dc9f98..83a325c8 100644
--- a/base/ltclass.dtx
+++ b/base/ltclass.dtx
@@ -2001,7 +2001,7 @@
 \def\@fileswith@pti@ns#1[#2]#3[#4]{%
   \ifx#1\@clsextension
     \ifx\@classoptionslist\relax
-      \xdef\@classoptionslist{\zap@space#2 \@empty}%
+      \protected@xdef\@classoptionslist{\zap@space#2 \@empty}%
 %    \end{macrocode}
 % Save raw class list.
 %    \begin{macrocode}
diff --git a/base/ltdefns.dtx b/base/ltdefns.dtx
index 9e1fa43f..11d51920 100644
--- a/base/ltdefns.dtx
+++ b/base/ltdefns.dtx
@@ -968,7 +968,7 @@
 %    A macro to totally expand two arguments to another macro
 %    \begin{macrocode}
 \def\@expandtwoargs#1#2#3{%
-\edef\reserved@a{\noexpand#1{#2}{#3}}\reserved@a}
+\protected@edef\reserved@a{\noexpand#1{#2}{#3}}\reserved@a}
 %    \end{macrocode}
 % \end{macro}
 %
```

But without the `\ ` this works:

```
\documentclass[foo,bar,baz=foo,ggg=sqrt{4}]{myclass}
\begin{document}
\end{document}
```

Giving

```
LaTeX Warning: Unused global option(s):
    [bar,ggg=sqrt{4}].
```

However (since 2021/02/18) the classic option handler strips the values here

```
\documentclass[foo,bar,baz=foo,ggg=sqrt{4}]{article}
\begin{document}
\end{document}
```

gives

```
LaTeX Warning: Unused global option(s):
    [foo,bar,baz,ggg].
```

I think just testing the key name is "known" is logically cleaner and practically the `{}` break the `\ifin@` tests in later package loading.

**Comment by josephwright** [comment]
@davidcarlisle  I'd got the wrong argument being added to `\@unusedoptionlist`: that's fixed by 737ca6476051c6189396eda272d7b0667e074055. I've not added a test file as this shows in `gitub-0892` anyway: OK?

**Comment by josephwright** [comment]
@davidcarlisle  You going to make additional changes for #933?

**Comment by davidcarlisle** [comment]
thanks I'll pull here and see ... (I suspect still missing some `\protect` guards if the amsmath example at the top of my review is to work (although really that's the other issue so we could perhps merge /close this one anywy and re-open  #933, let me test the last commit.

**Review by davidcarlisle — APPROVED** [review]
This looks good now, with the extra protected@edef this works

```
\documentclass[foo,bar,baz=foo,ggg=\sqrt{4}]{myclass}
\usepackage{amsmath}
\begin{document}
\end{document}
```

However it fails with `article`

```
! Missing \endcsname inserted.
<to be read again> 
                   \protect 
```

That may be fixable or we may live with constraints on passing kv options to classes not expecting them.

So I think this PR may be merged and then we can make a PR for #933 again branching off the updated develop branch allowing easier testing with everything in place

**Comment by josephwright** [comment]
> So I think this PR may be merged and then we can make a PR for #933 again branching off the updated develop branch allowing easier testing with everything in place

Cool: I'll do that once the test suite confirms a pass.

**Pull request merged**
