### PR TITLE
Add 13pt and 14pt type sizes to letter.cls

### PR DESCRIPTION
**Pull request by nikolas**
**READ ME FIRST**: Please understand that in most cases we will not be able to merge a pull request because there are a lot of internal activities needed when updating the LaTeX2e sources. If you have a code suggestion please discuss it with the team first.

*Pull requests in this repository are intended for LaTeX Team members only.*

# Internal housekeeping

## Status of pull request

- Feedback wanted 
- Ready to merge

## Checklist of required changes before merge will be approved
- [ ] Test file(s) added
- [x] Version and date string updated in changed source files
- [ ] Relevant `\changes` entries in source included
- [ ] Relevant `changes.txt` updated
- [ ] Rollback provided (if necessary)?
- [ ] `ltnewsX.tex` (and/or `latexchanges.tex`) updated

### CODE REVIEW

**Comment by davidcarlisle** [comment]
Sorry but the standard classes could not be changed in such a way at this point in time.

Apart from that any change would need to be accompanied by test files and supporting documentation.  The suggested change here would just define a `13pt` option that gave file not found errors for a missing `size13.clo`.

**Comment by nikolas** [comment]
Understood - I was just composing something with `letter.cls` and wanted to increase the type size to 14pt. What is the recommended way of altering type using letter.cls? It appears to only support 10pt, 11pt, and 12pt.

**Comment by davidcarlisle** [comment]
why the title change? 

Sorry but this is a bug tracking mechanism, not a support forum. The code you suggested (had you tried it) had no code to load fonts at different sizes, it just declared new options with no code so they would generate errors.

look at the `extletter` class from https://ctan.org/tex-archive/macros/latex/contrib/extsizes

**Comment by nikolas** [comment]
This line:
```
\DeclareOption{14pt}{\renewcommand\@ptsize{4}}
```

Allows me to specify `\documentclass[14pt]{letter}` in my tex document. I opened this pull request because this solved the issue for me and thought others could benefit. I'm not an expert in the workings of tex so it seems there are things preventing us from adding new options to this class. Could you be more specific on why we can't add more sizing options here? I'm just curious.

**Comment by davidcarlisle** [comment]
I'll reply once more but please in future  ask such questions in a more suitable forum eg https://tex.stackexchange.com This pull request is closed.

You defined `\documentclass[14pt]{letter}`  but you defined no code to load 14pt fonts.
All that will happen is that the class will execute `\input{size14.clo}` which by default does not exist so you will get a file not found error and no usable output.

If you had followed the guidelines in the pull request template and provided a test file showing the code running, you would have seen that it did not work (or that it used a file `size14.clo` that you have locally but have not provided)

**Pull request closed without merging**
