### PR TITLE
rewrite to use a safer UTF-8 decoder

### PR DESCRIPTION
**Pull request by mirabilos**
This has two slight API changes:

 * `\UTFviii@check@continue` (an internal but documented macro) is gone
 * the calling convention of `\UTFviii@checkseq` changes from
  `\if\relax\expandafter\UTFviii@checkseq\string#1\relax\relax%` to
  `\if\relax\expandafter\UTFviii@checkseq\string#1\empty\relax%`

Please check (as you told me on the TeX.SE chat you do when introducing changes like these) that there are no external users of either `\UTFviii@check@continue` (there should not be any, as it only makes sense inside checkseq) or `\UTFviii@checkseq` (in which case this would need to be changed).

The internal, _un_documented macros `\UTFviii@cleanup` and `\dec@de@UTFviii` are also gone; these only made sense within `\decode@UTFviii` and therefore should not have any callers either.

### CODE REVIEW

**Comment by davidcarlisle** [comment]
Thanks for this, but my initial reaction is that this is showing diminishing returns, it is adding a lot of code for very minor edge case of malfomred UTF-8. The overwhelmingly most common reason for malformed UTF-8 sequences is that the file isn't UTF-8 at all, so the important thing is to flag an error, detailed byte level checking isn't that useful.

The one test case that changed  the new code saves one loop, in that currently you get a "not set up" error but if you try to declare that number you get an error that the number is out of range. With this change you get an error that the initial byte sequence is invalid, which isn't clearly an improvement for most users. Either way it's just changing the error message, not catching something that was previously not an error.

I'll leave open for a bit to allow review from others.

**Comment by davidcarlisle** [comment]
> It *does* newly catch non-minimal-encoding malformed characters, such as using "C1 "80 for "40 (@). 

well not really as (without poking into the internals, and if users do that they can circumvent all checks) the only way to declare a character is by number and that will use the canonical minimal utf8 sequence so you should always get a "not set up" error for  bad sequences, or as in the case of C1 *0 you already get

`! Package inputenc Error: Invalid UTF-8 byte "C1.`

**Comment by mirabilos** [comment]
David Carlisle dixit:

>sequence so you should always get a "not set up" error for bad

I’ve been able to actually set up bad sequences.

>sequences, or as in the case of C1 *0 you already get
>
>`! Package inputenc Error: Invalid UTF-8 byte "C1.`

Yesssss, which is why I wrote

>>… (This is just an example of
>>non-minimal encoding, not one of the actual things caught, there
>>are others, and the C0/C1 case is easy to catch, but something
>>in the three- or four-byte encoding forms isn’t.)

**Comment by davidcarlisle** [comment]
> I’ve been able to actually set up bad sequences.
by defining the internal csname by hand, or do you mean that it's possible without defining internal commands to have a file with a bad utf-8 sequence to pass without error? I can't currently see that.

**Comment by mirabilos** [comment]
>by defining the internal csname by hand, or do you mean that it's
>possible without defining internal commands to have a file with a bad
>utf-8 sequence to pass without error? I can't currently see that.

I think it was possible, but I would have to try and reproduce it
again. I’m currently somewhat deep in other contexts…

**Comment by davidcarlisle** [comment]
Thanks again for this series  of PRs they definitely improved the UTF-8 handling, however as noted in comments above, this final one is adding delicate code that is only changing which error message is generated. Especially as UTF-8 is now enabled by default in LaTeX so this would affect the code paths in every latex document,  it is not clear the benefits are enough to justify the risks, we plan to close with no action.

**Pull request closed without merging**
