### PR TITLE
Add firstaid for acro

### PR DESCRIPTION
**Pull request by josephwright**
**READ ME FIRST**: Please understand that in most cases we will not be able to merge a pull request because there are a lot of internal activities needed when updating the LaTeX2e sources. If you have a code suggestion please discuss it with the team first.

*Pull requests in this repository are intended for LaTeX Team members only.*

# Internal housekeeping

## Status of pull request

- Feedback wanted 
- Under development
- [x] Ready to merge

## Checklist of required changes before merge will be approved
- [ ] Test file(s) added
- [x] Version and date string updated in changed source files
- [ ] Relevant `\changes` entries in source included
- [x] Relevant `changes.txt` updated
- [ ] Rollback provided (if necessary)?
- [ ] `ltnewsX.tex` (and/or `latexchanges.tex`) updated

### CODE REVIEW

**Comment by muzimuzhi** [comment]
With l3kernel 2024-02-18 (or maybe 2024-02-20), loading `acro` won't raise errors any more, and since `acro.sty` always [clears `\l__acro_tmpa_prop` before setting to it](https://github.com/cgnieder/acro/blob/9a56e414b0eb82ff89241decc66da9620f2292df/code/acro.sty#L1114-L1129), it seems to me there's no urgent need to firstaid `acro`.

**Comment by josephwright** [comment]
@muzimuzhi  Bruno's patch to make that work is meant to be temporary. I'm trying to cover the case where someone installs the TL'24 ISO then updates just `expl3`: ideally that should 'just work' even if we remove Bruno's patch (for performance reasons).

**Review by FrankMittelbach — APPROVED** [review]
Can't see anything wrong with this and giving the timeline I would apply the firstaid.

**Comment by josephwright** [comment]
@FrankMittelbach  Good to go for all three?

**Comment by FrankMittelbach** [comment]
guess so, but they probably don't play if merged one after another (without further updating) or do they?

**Comment by josephwright** [comment]
No but I'll sort that :)

**Pull request merged**
