### PR TITLE
Lthooks new showhook 2

### PR DESCRIPTION
**Pull request by jlaurens**
- tests for arguments
- show test file frozen for the 2023-06-01 release
- show test file for the latest release, will be used to change `\ShowHook` in a forthcoming PR

No date change, no code change

2 commits, the first one is the same as in PR #1248

*Pull requests in this repository are intended for LaTeX Team members only.*

# Internal housekeeping

## Status of pull request

- Feedback wanted 
- Under development
- Ready to merge

## Checklist of required changes before merge will be approved
- [ X] Test file(s) added
- [ ] Version and date string updated in changed source files
- [ ] Relevant `\changes` entries in source included
- [ ] Relevant `changes.txt` updated
- [ ] Rollback provided (if necessary)?
- [ ] `ltnewsX.tex` (and/or `latexchanges.tex`) updated

### CODE REVIEW

**Comment by jlaurens** [comment]
Changing the name of the frozen tests to conform to the other names. Force pushed because another PR is relying on that.

**Comment by jlaurens** [comment]
Test names conform to other frozen tests names.

**Comment by josephwright** [comment]
I'm not sure I see the difference between this PR and https://github.com/latex3/latex2e/pull/1248 in a functional sense: could you explain a bit more?

**Comment by jlaurens** [comment]
Maybe one dedicated branch for this PR and the forthcoming ones before everything is organized into bigger commits and merged to develop

**Comment by josephwright** [comment]
@jlaurens From what I can see, this PR should be merged as it includes everything from #1248. Assuming that's correct, I can look to rebase tomorrow and get merged.

**Pull request closed without merging**
