### PR TITLE
guillemet issue #65

### PR DESCRIPTION
**Pull request by davidcarlisle**
## Status of pull request

- Ready to merge

## Checklist of required changes before merge will be approved
- [ ] Test file(s) added
- [X] Version and date string updated in changed source files
- [ ] Relevant `\changes` entries in source included
- [X] Relevant `changes.txt` updated
- [ ] `ltnewsX.tex` (and/or `latexchanges.tex`) updated

PR against develop, I guess we'd merge to main and update cyrillic on ctan from there along with the patch release

### CODE REVIEW

**Review by FrankMittelbach — APPROVED** [review]
looks ok to me, but it needs to be merged into main as well as develop.

**Comment by davidcarlisle** [comment]
> looks ok to me, but it needs to be merged into main as well as develop.

yes wasn't sure of best order. Merge this PR then rebase it from devel to main?

**Comment by davidcarlisle** [comment]
changing to target main using the GUI above makes it want to change to much. I guess I need to merge in just the one commit using the CLI locally

**Comment by FrankMittelbach** [comment]
> changing to target main using the GUI above makes it want to change to much. I guess I need to merge in just the one commit using the CLI locally

yes, that usually doesn't work, which is why I think it is best to base hotfixes off main and then merge the branch also to develop, but cherry-picking as you did does work too, of course (but is more work)

**Pull request merged**
