### PR TITLE
lthooks: new `\ShowHook` command

### PR DESCRIPTION
**Pull request by jlaurens**
**READ ME FIRST**: Please understand that in most cases we will not be able to merge a pull request because there are a lot of internal activities needed when updating the LaTeX2e sources. If you have a code suggestion please discuss it with the team first.

This PR is on top of PR #1249 and PR #1248, only the 3rd commit is original.

Changes in `lthooks.dtx`:
- The actual `\@@_log:nN` has been pushed for rollback with the `2023-06-01` tag.
- A new `\@@_log:nN` is provided.

Changes in `lthooks-show.lvt`
- new tests with rule compatibility (output focuses on warning and errors)

Changes in `lthooks-show.lgt`
- this is exactly where the difference between old and new output is enlighten, diff helps a lot

Forthcoming work:
- in tests that are not frozen, replace `\ShowHook` with a more appropriate`\DebugPrintHook`, actually in progress and quite complete
- update the `*.lgt` (actually many tests fail because of the new `\ShowHook` output)

This will make this PR complete

*Pull requests in this repository are intended for LaTeX Team members only.*

# Internal housekeeping

## Status of pull request

- Feedback wanted 
- Under development

## Checklist of required changes before merge will be approved
- [x] Test file(s) added
- [ ] Version and date string updated in changed source files
- [ ] Relevant `\changes` entries in source included
- [ ] Relevant `changes.txt` updated
- [ ] Rollback provided (if necessary)?
- [ ] `ltnewsX.tex` (and/or `latexchanges.tex`) updated

### CODE REVIEW

**Comment by jlaurens** [comment]
I still have problems with checks, locally everything runs fine but on the remote, there are errors

**Comment by u-fischer** [comment]
> I still have problems with checks, locally everything runs fine but on the remote, there are errors

some of the `required/firstaid` tests fail for me locally too due to the changes of the PR. E.g. with this diff.

~~~~
***** ..\..\BUILD\TEST-CONFIG-TU\firstaid-bidi.luatex.tlg
    2:  Don't change this file in any respect.
    3:  -> The generic hook 'file/biditools.sty/after':
    4:  > The hook is not declared.
    5:  > The hook is empty.
    6:  <recently read> }
***** ..\..\BUILD\TEST-CONFIG-TU\FIRSTAID-BIDI.LUATEX.LOG
    2:  Don't change this file in any respect.
    3:  ==> Hook: 'file/biditools.sty/after'
    4:  >   builtin generic.
    5:  <recently read> }
*****
~~~~

**Comment by jlaurens** [comment]
Yes, that part was easy to fix. My problems are with
```
*** ../../build/test-config-toc/toc-ex-book-hyperref-1.tpf	Sat Jan 27 15:47:58 2024
--- ../../build/test-config-toc/toc-ex-book-hyperref-1.pdftex.pdf	Sat Jan 27 15:48:02 2024
***************
*** 1773,1845 ****
  << /Marked true  >>
  endobj
  319 0 obj
! << /S /GoTo /D (chapter.1) /SD 115 0 R >>
  endobj
 ```

**Comment by u-fischer** [comment]
> toc-ex-book-hyperref-1

I don't see this error in your last github check (and locally it works too). But `minipage-005-footnote` errors because of the changed hook messages.

**Comment by jlaurens** [comment]
After stronger and cleaner processing (I am still learning), here are rebased commits
- 1st commit to define before/after `\ShowHook` output
- 2nd commit to define `\ShowHook`. Checks passed locally at the top level.
- 3rd commit to define `\DebugPrintHook` because `\ShowHook` does not fit for testing. Checks passed locally at the top level. Doc builds at the top level

Please notice that `base/testfiles-search/tlb-CJK-001.tlg` is changed more than expected: there is an added `\@forced@seriesfalse` on line 6. It might be expected though.

**Comment by jlaurens** [comment]
The top level checks do not pass for me locally, more precisely the `config-toc` in the `required/latex-lab` fails. Maybe this is expected.

**Comment by josephwright** [comment]
Could you rebase onto develop here - I think things look like they are close to ready for review?

**Comment by jlaurens** [comment]
Too complicated to rebase
I will open another pull request

**Pull request closed without merging**
